language: generic
sudo: false
branches:
  only:
    - master
    - develop
before_install:
  - git clone https://github.com/rejeep/evm.git /home/travis/.evm
  - export PATH="/home/travis/.evm/bin:$PATH"
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip
  - mkdir -p ~/.config/doom
  - cp init.test.el ~/.config/doom/init.el
  - INSECURE=1 YES=1 make install
env:
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26-pretest-travis
script:
  - emacs --version
  - DEBUG=1 make test
